const test = [
  {
    createdAt: '2021-12-27T20:00:59.994Z',
    name: 'Ms. Raymond Collins',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '543.00',
    rating: '972701246',
    amount: '244.73',
    category: 'category 1',
    size: 'size 1',
    color: 'orchid',
    wearType: 'wearType 1',
    description: 'Ipsum sit voluptatem accusantium maiores id qui dolor.',
    about:
      'Et quam ut. Libero laudantium rerum reiciendis debitis qui at ut ut soluta. Est itaque sapiente quo dolore nulla et. Possimus et nemo architecto molestias optio dolores ea voluptatem voluptates. Ducimus doloremque eveniet voluptatem corrupti et non dolores.',
    id: '1'
  },
  {
    createdAt: '2021-12-27T18:11:40.901Z',
    name: 'Marlene Abernathy',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '535.00',
    rating: '225800140',
    amount: '227.03',
    category: 'category 2',
    size: 'size 2',
    color: 'mint green',
    wearType: 'wearType 2',
    description: 'Voluptatem rerum consequatur cum molestiae ipsum sit corporis labore.',
    about:
      'Fuga quis quisquam eos veritatis enim nemo voluptas ut non. Ea nostrum quia. Voluptatem nam incidunt autem optio ratione quibusdam velit animi assumenda. Est cumque quia optio pariatur repellat suscipit quod et ut.',
    id: '2'
  },
  {
    createdAt: '2021-12-28T12:35:39.084Z',
    name: 'Clint Haag',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '757.00',
    rating: '226473848',
    amount: '273.91',
    category: 'category 3',
    size: 'size 3',
    color: 'magenta',
    wearType: 'wearType 3',
    description: 'Et nulla eos quisquam omnis consectetur asperiores eius consequatur officia.',
    about:
      'Nemo magni excepturi perspiciatis voluptatum similique. Explicabo voluptates repellat molestias omnis est facere. Voluptates cumque officiis sit facilis. Consectetur officia aut nostrum facere.',
    id: '3'
  },
  {
    createdAt: '2021-12-27T20:21:49.243Z',
    name: 'Dominic Jacobson',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '397.00',
    rating: '039779522',
    amount: '149.09',
    category: 'category 4',
    size: 'size 4',
    color: 'teal',
    wearType: 'wearType 4',
    description: 'Atque aperiam voluptas maiores unde vel vero.',
    about:
      'Rerum consequatur temporibus est natus. Quia eius voluptate. Officiis rerum nemo. Porro explicabo voluptatem consequatur et voluptas libero amet. Nesciunt perspiciatis fugit. Dolores ex ea.',
    id: '4'
  },
  {
    createdAt: '2021-12-27T18:06:06.973Z',
    name: 'Claude Schoen',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '275.00',
    rating: '811675116',
    amount: '497.69',
    category: 'category 5',
    size: 'size 5',
    color: 'sky blue',
    wearType: 'wearType 5',
    description: 'Voluptatibus et facere similique odit similique molestiae dolor rerum molestiae.',
    about:
      'Aut facere ad sequi laboriosam modi. Rerum inventore ipsum officia ipsa neque maiores doloremque. Et aut et ratione. Ipsum nihil et corporis et ad.',
    id: '5'
  },
  {
    createdAt: '2021-12-27T21:11:13.375Z',
    name: 'Bradford Barrows',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '688.00',
    rating: '610715594',
    amount: '338.60',
    category: 'category 6',
    size: 'size 6',
    color: 'olive',
    wearType: 'wearType 6',
    description: 'Et necessitatibus laboriosam consequuntur quos possimus ullam.',
    about:
      'Dolor dolorem quos sunt placeat culpa maxime tenetur. Neque dolores qui temporibus ducimus vitae eos molestiae nam consequuntur. Quia vitae qui consequuntur. Quis impedit eveniet enim qui hic. Qui ratione harum maxime praesentium optio laborum. Aut at molestias excepturi debitis.',
    id: '6'
  },
  {
    createdAt: '2021-12-28T08:28:30.105Z',
    name: 'Ms. Shawn Jakubowski',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '473.00',
    rating: '975102473',
    amount: '678.46',
    category: 'category 7',
    size: 'size 7',
    color: 'black',
    wearType: 'wearType 7',
    description: 'Et et eligendi assumenda cumque rerum assumenda.',
    about:
      'Enim rem nemo possimus. Id corporis alias iste. Sunt rerum est aut et temporibus saepe. Cumque laborum sit aperiam. Et dolorum quisquam dignissimos nesciunt sit.',
    id: '7'
  },
  {
    createdAt: '2021-12-28T08:02:22.925Z',
    name: 'Cecelia Hintz',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '460.00',
    rating: '906966206',
    amount: '584.36',
    category: 'category 8',
    size: 'size 8',
    color: 'turquoise',
    wearType: 'wearType 8',
    description: 'Repellat quam aperiam voluptatum quia nihil voluptatum eveniet.',
    about:
      'Labore rerum nam quia eveniet delectus aut. Aliquid et eum amet sit et tempore. Pariatur est nihil odio aut ad ex consequatur modi. Voluptates quibusdam perferendis repellat ex ipsa sit tempora odio recusandae. Sit atque eum quo cumque delectus.',
    id: '8'
  },
  {
    createdAt: '2021-12-28T12:49:47.397Z',
    name: 'Opal Grant DVM',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '785.00',
    rating: '958924979',
    amount: '587.34',
    category: 'category 9',
    size: 'size 9',
    color: 'green',
    wearType: 'wearType 9',
    description: 'Alias omnis ducimus.',
    about:
      'Nam sed omnis. Est voluptates tempora aut omnis eius molestias. Ut saepe illo amet doloremque dolorem aut sit. Quia et praesentium dolor occaecati itaque et odio assumenda officiis. Laboriosam possimus esse.',
    id: '9'
  },
  {
    createdAt: '2021-12-27T20:22:11.100Z',
    name: 'Marlene Johns',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '996.00',
    rating: '878947780',
    amount: '226.94',
    category: 'category 10',
    size: 'size 10',
    color: 'tan',
    wearType: 'wearType 10',
    description: 'Aut dolorum odit.',
    about: 'Repudiandae deserunt dignissimos. Ut et ea et.',
    id: '10'
  },
  {
    createdAt: '2021-12-28T05:50:33.395Z',
    name: 'Arnold Miller I',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '477.00',
    rating: '145635822',
    amount: '876.02',
    category: 'category 11',
    size: 'size 11',
    color: 'orange',
    wearType: 'wearType 11',
    description: 'Accusantium et dolores odit dolorum nisi magni facilis deleniti.',
    about: 'Nisi accusantium voluptas. Perspiciatis deserunt quia consequatur non.',
    id: '11'
  },
  {
    createdAt: '2021-12-27T18:46:59.186Z',
    name: 'Bethany Lang',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '406.00',
    rating: '946103236',
    amount: '97.77',
    category: 'category 12',
    size: 'size 12',
    color: 'white',
    wearType: 'wearType 12',
    description: 'Fugiat sapiente voluptates similique.',
    about:
      'Tempora nulla fuga vero quae qui molestias similique ullam. Omnis ut rerum non nostrum laborum modi. Dicta dignissimos laborum dolor dolorum repellat enim ipsam occaecati quasi.',
    id: '12'
  },
  {
    createdAt: '2021-12-28T14:11:49.779Z',
    name: 'Sarah Monahan',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '169.00',
    rating: '310101725',
    amount: '701.78',
    category: 'category 13',
    size: 'size 13',
    color: 'grey',
    wearType: 'wearType 13',
    description: 'Eligendi enim natus ex.',
    about:
      'Hic incidunt cumque fuga officiis. Et id tenetur doloremque rerum modi modi nihil. Velit quisquam accusantium quidem.',
    id: '13'
  },
  {
    createdAt: '2021-12-28T02:27:20.469Z',
    name: 'Dr. Lena Smith',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '643.00',
    rating: '891378190',
    amount: '216.99',
    category: 'category 14',
    size: 'size 14',
    color: 'purple',
    wearType: 'wearType 14',
    description: 'Necessitatibus sunt voluptas tenetur aut omnis ea nam.',
    about:
      'Ut aut dolor eos sint veritatis ut culpa laboriosam delectus. Praesentium et libero fuga alias nam eum et quia qui. Tempora ex perspiciatis omnis autem quae rerum voluptas. Explicabo reprehenderit qui quas ut maxime. Ex harum architecto nostrum sed id. Veniam sapiente architecto quo aut.',
    id: '14'
  },
  {
    createdAt: '2021-12-28T10:58:34.724Z',
    name: 'Rickey Wiegand',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '12.00',
    rating: '232624908',
    amount: '457.41',
    category: 'category 15',
    size: 'size 15',
    color: 'grey',
    wearType: 'wearType 15',
    description: 'Quasi amet natus eos est nam.',
    about: 'Fuga eum dolorem enim quis sit aut error commodi. Ducimus est soluta tempore cumque quam et aut.',
    id: '15'
  },
  {
    createdAt: '2021-12-27T18:24:18.966Z',
    name: 'Angel Jacobi III',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '173.00',
    rating: '025965890',
    amount: '979.49',
    category: 'category 16',
    size: 'size 16',
    color: 'orchid',
    wearType: 'wearType 16',
    description: 'Labore dignissimos est dolore dolores ipsam.',
    about: 'Et et ea aspernatur consequatur rerum consequatur. Autem amet amet quas quo provident.',
    id: '16'
  },
  {
    createdAt: '2021-12-28T07:05:26.740Z',
    name: 'Roberta Nader',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '936.00',
    rating: '623258844',
    amount: '442.41',
    category: 'category 17',
    size: 'size 17',
    color: 'fuchsia',
    wearType: 'wearType 17',
    description: 'Dolore praesentium rerum tempore quam aperiam ut iusto.',
    about:
      'Aliquid pariatur dolores aut. Culpa et eligendi sunt error velit sit. Eos impedit impedit aut autem aliquam atque voluptate sed. Sint repellendus in fugit voluptates delectus eum sed. Quis et ea doloribus natus tempore enim autem.',
    id: '17'
  },
  {
    createdAt: '2021-12-28T02:21:23.271Z',
    name: 'Nadine Lehner',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '366.00',
    rating: '055068819',
    amount: '945.68',
    category: 'category 18',
    size: 'size 18',
    color: 'teal',
    wearType: 'wearType 18',
    description: 'Nihil dolorum rerum eius nostrum.',
    about: 'Molestiae rerum quae deleniti sit. Totam rerum et aperiam aut vel exercitationem id.',
    id: '18'
  },
  {
    createdAt: '2021-12-28T09:29:59.203Z',
    name: 'Drew Prohaska',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '489.00',
    rating: '105825258',
    amount: '72.05',
    category: 'category 19',
    size: 'size 19',
    color: 'sky blue',
    wearType: 'wearType 19',
    description: 'Rerum iusto vitae aut voluptatem velit adipisci qui aut unde.',
    about:
      'Voluptatum soluta illum corporis totam maxime aliquam voluptatibus. Aut dicta quo autem in modi impedit placeat et.',
    id: '19'
  },
  {
    createdAt: '2021-12-28T06:57:00.446Z',
    name: 'Catherine Emard Sr.',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '741.00',
    rating: '569574873',
    amount: '838.77',
    category: 'category 20',
    size: 'size 20',
    color: 'teal',
    wearType: 'wearType 20',
    description: 'Sit itaque cumque accusamus cumque.',
    about:
      'Soluta rerum ratione consequatur soluta beatae tenetur omnis. Vitae repellat et quod porro nemo dicta earum omnis incidunt. Recusandae voluptatem ut quos. Debitis nemo in voluptates iure deleniti libero. Ut impedit quae culpa neque assumenda qui sequi animi.',
    id: '20'
  },
  {
    createdAt: '2021-12-28T13:50:33.514Z',
    name: 'Nadine Buckridge I',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '944.00',
    rating: '639895974',
    amount: '102.69',
    category: 'category 21',
    size: 'size 21',
    color: 'orchid',
    wearType: 'wearType 21',
    description: 'Labore repudiandae atque qui officia voluptatibus aut.',
    about:
      'Ipsa vero magni temporibus quos repudiandae velit minus molestiae. Velit modi error sequi molestiae unde sapiente ullam. Saepe quis facere non libero quis vitae eligendi rem rerum.',
    id: '21'
  },
  {
    createdAt: '2021-12-28T04:04:40.099Z',
    name: 'Fannie Turcotte',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '936.00',
    rating: '557633289',
    amount: '918.30',
    category: 'category 22',
    size: 'size 22',
    color: 'lavender',
    wearType: 'wearType 22',
    description: 'Eaque error voluptatem molestiae porro vel fuga sit soluta suscipit.',
    about:
      'Ea ut suscipit consequatur illum quod quia et quibusdam. Veniam aut ea corrupti eveniet tempore facere rem enim deserunt. Nesciunt repudiandae iusto voluptatem voluptatem dolor. Aut ad ullam amet et ipsam eum incidunt possimus ut.',
    id: '22'
  },
  {
    createdAt: '2021-12-28T00:40:45.825Z',
    name: 'Judith Schmidt',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '31.00',
    rating: '700362161',
    amount: '116.22',
    category: 'category 23',
    size: 'size 23',
    color: 'lavender',
    wearType: 'wearType 23',
    description: 'Explicabo dolor reprehenderit neque libero aliquid aspernatur odit.',
    about:
      'Ut et in necessitatibus enim labore qui et dicta suscipit. Sint corrupti ut. Maxime accusantium repellat omnis.',
    id: '23'
  },
  {
    createdAt: '2021-12-27T20:13:14.140Z',
    name: 'Pablo Schimmel',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '30.00',
    rating: '758508595',
    amount: '778.73',
    category: 'category 24',
    size: 'size 24',
    color: 'pink',
    wearType: 'wearType 24',
    description: 'Quasi enim cupiditate hic ut non quia maxime explicabo.',
    about:
      'Veniam aut maiores sed rem quam impedit aut voluptatum. Qui sunt fuga. Omnis ullam quia adipisci aut. Quasi qui fugit alias deleniti. Aliquid perferendis quia similique cumque tenetur nihil autem et.',
    id: '24'
  },
  {
    createdAt: '2021-12-27T18:45:36.780Z',
    name: 'Francis Robel',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '731.00',
    rating: '660284538',
    amount: '955.43',
    category: 'category 25',
    size: 'size 25',
    color: 'pink',
    wearType: 'wearType 25',
    description: 'Quo velit voluptas ducimus vel at nesciunt perspiciatis.',
    about:
      'Incidunt eos enim dicta nam maxime dolore aut illum et. Voluptas a ipsum odit laborum et deleniti. Reprehenderit omnis vel maiores quisquam exercitationem autem.',
    id: '25'
  },
  {
    createdAt: '2021-12-27T19:06:36.905Z',
    name: 'Whitney Tillman',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '466.00',
    rating: '654696080',
    amount: '346.13',
    category: 'category 26',
    size: 'size 26',
    color: 'green',
    wearType: 'wearType 26',
    description: 'Commodi aut iusto vitae accusamus eius vel molestias veritatis reprehenderit.',
    about: 'Doloremque reiciendis exercitationem. Nam saepe fugiat ipsum autem.',
    id: '26'
  },
  {
    createdAt: '2021-12-28T00:49:50.670Z',
    name: 'Nettie Abernathy',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '166.00',
    rating: '329920476',
    amount: '89.85',
    category: 'category 27',
    size: 'size 27',
    color: 'maroon',
    wearType: 'wearType 27',
    description: 'Reiciendis delectus beatae iusto.',
    about: 'Quae magni voluptatem ut qui est dolores voluptate sunt. Ipsam deleniti modi voluptate illum.',
    id: '27'
  },
  {
    createdAt: '2021-12-27T20:11:14.347Z',
    name: 'Michele Sanford DVM',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '408.00',
    rating: '913850635',
    amount: '776.57',
    category: 'category 28',
    size: 'size 28',
    color: 'lime',
    wearType: 'wearType 28',
    description: 'Tempora quaerat culpa quisquam laudantium odit non cum voluptatem.',
    about: 'Numquam est incidunt fugiat amet ut et eveniet ratione. Et et voluptatem impedit odio saepe.',
    id: '28'
  },
  {
    createdAt: '2021-12-28T00:58:19.856Z',
    name: 'Marcus Lesch IV',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '4.00',
    rating: '114060499',
    amount: '796.24',
    category: 'category 29',
    size: 'size 29',
    color: 'orchid',
    wearType: 'wearType 29',
    description: 'Alias quo placeat occaecati vel impedit vitae eveniet omnis rerum.',
    about:
      'Aut minus animi distinctio. Quisquam similique iusto explicabo itaque. Veniam sunt eaque accusantium qui quam dolor quaerat nesciunt animi. Accusamus dolorem in harum voluptatem iste. Earum expedita qui. Vero repellendus ipsa necessitatibus eos.',
    id: '29'
  },
  {
    createdAt: '2021-12-27T17:54:02.576Z',
    name: 'Sammy Fritsch',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '642.00',
    rating: '847993639',
    amount: '343.62',
    category: 'category 30',
    size: 'size 30',
    color: 'pink',
    wearType: 'wearType 30',
    description: 'Molestiae consequatur qui non.',
    about: 'Modi deserunt pariatur eos beatae dolorem eaque quam officiis quis. Earum consectetur et nemo.',
    id: '30'
  },
  {
    createdAt: '2021-12-28T11:30:50.791Z',
    name: 'Edmund Price',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '986.00',
    rating: '483495070',
    amount: '39.40',
    category: 'category 31',
    size: 'size 31',
    color: 'red',
    wearType: 'wearType 31',
    description: 'Aut quia aut.',
    about: 'Esse commodi et doloribus non tempore minima enim consequuntur ab. Quidem delectus repudiandae et.',
    id: '31'
  },
  {
    createdAt: '2021-12-28T03:14:08.255Z',
    name: 'Bertha Beahan',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '900.00',
    rating: '762442456',
    amount: '103.71',
    category: 'category 32',
    size: 'size 32',
    color: 'plum',
    wearType: 'wearType 32',
    description: 'Omnis qui quia eveniet iure eum mollitia ratione.',
    about:
      'Quisquam odit voluptatibus omnis vel provident. At enim voluptas consectetur est et. Atque a repudiandae quibusdam facilis. Ut aut et illo iusto similique. Nostrum consectetur odio consequatur eos. Libero quod iure.',
    id: '32'
  },
  {
    createdAt: '2021-12-27T17:00:26.988Z',
    name: 'Traci Mante',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '417.00',
    rating: '787932475',
    amount: '990.84',
    category: 'category 33',
    size: 'size 33',
    color: 'fuchsia',
    wearType: 'wearType 33',
    description: 'Illo nam aut aperiam soluta dolor occaecati.',
    about:
      'Aliquid delectus incidunt et voluptas deserunt dolorem consectetur. Sunt esse officia ea id reprehenderit enim modi pariatur officia.',
    id: '33'
  },
  {
    createdAt: '2021-12-28T08:41:30.565Z',
    name: 'Gerald Nicolas',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '343.00',
    rating: '615994239',
    amount: '884.71',
    category: 'category 34',
    size: 'size 34',
    color: 'lavender',
    wearType: 'wearType 34',
    description: 'Vel animi dolorem vel tempore explicabo voluptas animi.',
    about: 'Voluptas repellendus quasi dolores a dolorem velit aut quibusdam. Molestiae maiores et consequatur id.',
    id: '34'
  },
  {
    createdAt: '2021-12-27T19:13:25.299Z',
    name: 'Rene Gaylord',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '708.00',
    rating: '474842441',
    amount: '976.48',
    category: 'category 35',
    size: 'size 35',
    color: 'tan',
    wearType: 'wearType 35',
    description: 'Odit libero maxime.',
    about:
      'Est necessitatibus cum eos autem. Et modi sed ullam. Laboriosam ea consequatur dolor neque laboriosam aliquid ipsam reiciendis. Iusto excepturi quia est iure corporis praesentium. Maxime et quaerat. Rem officia sed doloremque dolores in excepturi veritatis.',
    id: '35'
  },
  {
    createdAt: '2021-12-27T23:35:10.745Z',
    name: 'Clayton Lubowitz',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '551.00',
    rating: '809474374',
    amount: '649.57',
    category: 'category 36',
    size: 'size 36',
    color: 'mint green',
    wearType: 'wearType 36',
    description: 'Fugit vitae quis incidunt facilis provident porro est quasi explicabo.',
    about:
      'Quis fuga ea ipsam occaecati minima. Laudantium culpa ut quisquam molestiae non nulla. Non autem quia dignissimos.',
    id: '36'
  },
  {
    createdAt: '2021-12-27T19:33:24.633Z',
    name: 'Flora Collier',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '9.00',
    rating: '235548007',
    amount: '171.50',
    category: 'category 37',
    size: 'size 37',
    color: 'pink',
    wearType: 'wearType 37',
    description: 'Eum ratione esse rerum.',
    about: 'Nesciunt quas voluptatem autem deleniti maiores. Aut expedita eum nam sint. Non voluptatem id temporibus.',
    id: '37'
  },
  {
    createdAt: '2021-12-27T17:10:09.648Z',
    name: 'Brendan Upton',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '80.00',
    rating: '207122765',
    amount: '558.63',
    category: 'category 38',
    size: 'size 38',
    color: 'mint green',
    wearType: 'wearType 38',
    description: 'Sint aperiam suscipit facilis excepturi.',
    about:
      'Voluptate accusamus occaecati quos error quos. Omnis cumque optio nesciunt perspiciatis praesentium delectus consequatur laborum voluptas. Perferendis qui nostrum vitae ut dolores voluptatem. Asperiores id nisi ipsam est. Et cupiditate asperiores.',
    id: '38'
  },
  {
    createdAt: '2021-12-28T10:40:32.767Z',
    name: 'Pearl Lowe',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '251.00',
    rating: '879979032',
    amount: '544.07',
    category: 'category 39',
    size: 'size 39',
    color: 'violet',
    wearType: 'wearType 39',
    description: 'Nobis vitae nam deserunt aspernatur iure.',
    about:
      'Et labore ea pariatur rerum cupiditate est commodi exercitationem aut. Ducimus iure qui exercitationem ut et reiciendis tempora enim rerum. Ratione explicabo reprehenderit et atque beatae tempora ut ut.',
    id: '39'
  },
  {
    createdAt: '2021-12-28T10:33:23.344Z',
    name: 'Maxine Schinner',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '178.00',
    rating: '340611117',
    amount: '684.09',
    category: 'category 40',
    size: 'size 40',
    color: 'olive',
    wearType: 'wearType 40',
    description: 'Officia qui rerum cum eveniet et.',
    about:
      'Et a culpa omnis id in aliquam dolores id. Voluptatibus facere harum nisi modi accusantium at vel illo libero. Rem ea odio perspiciatis rem. Autem consectetur reprehenderit et sapiente ullam debitis possimus.',
    id: '40'
  },
  {
    createdAt: '2021-12-28T12:28:23.978Z',
    name: 'Marguerite Bednar',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '641.00',
    rating: '455775537',
    amount: '580.40',
    category: 'category 41',
    size: 'size 41',
    color: 'white',
    wearType: 'wearType 41',
    description: 'Dolorem nostrum quasi ipsum qui.',
    about:
      'Et natus aut quam. Enim rem eaque iste temporibus sed. Sapiente quibusdam omnis tenetur. Fuga aut laudantium non consequuntur et. Voluptatem consequatur ab et nisi suscipit magnam.',
    id: '41'
  },
  {
    createdAt: '2021-12-27T19:42:14.307Z',
    name: 'Lynda Morar',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '524.00',
    rating: '462194208',
    amount: '59.04',
    category: 'category 42',
    size: 'size 42',
    color: 'violet',
    wearType: 'wearType 42',
    description: 'Officiis sed quasi a ullam quia ut autem explicabo.',
    about:
      'Itaque ut officiis ducimus. Sapiente minima enim voluptatem est nam ratione. Sequi dolorem dignissimos nihil eligendi facilis mollitia. Est ea consectetur modi laboriosam alias quia voluptas.',
    id: '42'
  },
  {
    createdAt: '2021-12-28T15:13:19.124Z',
    name: 'Roberta Fay IV',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '831.00',
    rating: '265629556',
    amount: '680.51',
    category: 'category 43',
    size: 'size 43',
    color: 'fuchsia',
    wearType: 'wearType 43',
    description: 'Natus ex provident ducimus et atque placeat et qui consectetur.',
    about:
      'Facilis et eligendi eum quia ut. Odit omnis beatae nam fugiat vitae est. Vel est qui ipsum sed voluptatibus. Labore et rerum rerum omnis sit doloribus eligendi eum nemo. Numquam sint inventore consequatur nobis ipsa consequuntur.',
    id: '43'
  },
  {
    createdAt: '2021-12-28T11:29:21.756Z',
    name: 'Joanna MacGyver',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '195.00',
    rating: '717559527',
    amount: '72.93',
    category: 'category 44',
    size: 'size 44',
    color: 'sky blue',
    wearType: 'wearType 44',
    description: 'Quisquam similique fugiat aut itaque.',
    about: 'Et et et laborum illum in explicabo nobis. Alias velit dolores.',
    id: '44'
  },
  {
    createdAt: '2021-12-28T05:09:48.072Z',
    name: 'Harvey Cartwright',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '934.00',
    rating: '235787389',
    amount: '905.27',
    category: 'category 45',
    size: 'size 45',
    color: 'cyan',
    wearType: 'wearType 45',
    description: 'Accusantium velit aut et similique doloremque ut aliquid velit.',
    about:
      'Dolor cumque consequatur totam nesciunt. Aut libero quia est quam autem. Corrupti sequi nihil doloremque quia.',
    id: '45'
  },
  {
    createdAt: '2021-12-28T12:07:24.072Z',
    name: 'Mr. Jeffrey Donnelly',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '403.00',
    rating: '166851805',
    amount: '568.92',
    category: 'category 46',
    size: 'size 46',
    color: 'blue',
    wearType: 'wearType 46',
    description: 'Voluptas est atque.',
    about:
      'Exercitationem placeat qui quo odit aspernatur. Sunt tempora dolorem aut sit et suscipit animi. Inventore omnis veniam ipsam. Itaque facilis natus enim ab a nulla. Iste velit est modi voluptas dolor rem non.',
    id: '46'
  },
  {
    createdAt: '2021-12-27T16:19:36.542Z',
    name: 'Louis Ondricka',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '642.00',
    rating: '587344454',
    amount: '290.59',
    category: 'category 47',
    size: 'size 47',
    color: 'violet',
    wearType: 'wearType 47',
    description: 'Consequatur sint officiis sed qui blanditiis aliquam eveniet sunt et.',
    about:
      'Quia dolore aut voluptas tenetur. Doloremque dolorum quia nihil odit illo. Sint perspiciatis omnis sint ut enim. Autem velit aut illo et incidunt illo. Libero rerum rerum similique aut. Debitis itaque animi.',
    id: '47'
  },
  {
    createdAt: '2021-12-28T09:49:39.272Z',
    name: 'Mamie Buckridge',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '759.00',
    rating: '807330957',
    amount: '851.45',
    category: 'category 48',
    size: 'size 48',
    color: 'green',
    wearType: 'wearType 48',
    description: 'Et beatae sed laudantium.',
    about: 'Omnis voluptas cumque non similique vel. Sed ipsum architecto voluptatem exercitationem.',
    id: '48'
  },
  {
    createdAt: '2021-12-27T22:40:01.543Z',
    name: 'Randall Waters',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '236.00',
    rating: '433031167',
    amount: '20.85',
    category: 'category 49',
    size: 'size 49',
    color: 'salmon',
    wearType: 'wearType 49',
    description: 'Amet sapiente et ad.',
    about:
      'Corrupti vel autem aut saepe quasi qui eos aliquam id. Ea veniam aut rerum sit quae rem sit ratione eius. Eius nostrum nemo. Et ipsa vitae voluptatem. Et aliquid inventore a aut excepturi et.',
    id: '49'
  },
  {
    createdAt: '2021-12-28T04:19:54.853Z',
    name: 'Mitchell Legros IV',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '805.00',
    rating: '061482913',
    amount: '323.22',
    category: 'category 50',
    size: 'size 50',
    color: 'orchid',
    wearType: 'wearType 50',
    description: 'Et vero et sapiente cupiditate maiores facilis consequuntur reprehenderit.',
    about:
      'Aliquam aperiam non odit sit quam ipsum et. Earum ut quia. Totam eos cum quia dolor minima corrupti repellat. Aspernatur aspernatur impedit ratione voluptas quibusdam quasi accusantium maiores.',
    id: '50'
  },
  {
    createdAt: '2021-12-28T00:51:17.656Z',
    name: 'Bridget Daugherty',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '653.00',
    rating: '172189859',
    amount: '125.90',
    category: 'category 51',
    size: 'size 51',
    color: 'black',
    wearType: 'wearType 51',
    description: 'Voluptas distinctio sit et et commodi labore libero.',
    about:
      'Nulla iure sit. Id sed nihil modi autem quia ut. Sit consequatur laudantium possimus eos illum voluptate architecto sit.',
    id: '51'
  },
  {
    createdAt: '2021-12-27T20:27:38.048Z',
    name: 'Clark Lemke',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '690.00',
    rating: '482433677',
    amount: '45.88',
    category: 'category 52',
    size: 'size 52',
    color: 'grey',
    wearType: 'wearType 52',
    description: 'Omnis et natus dolores dignissimos vitae praesentium.',
    about:
      'Voluptatem placeat libero accusamus rerum aut possimus placeat. Deleniti blanditiis ut est ipsum asperiores. Nemo sit voluptas saepe quas quisquam in. Consequatur id officia autem expedita quaerat qui. Molestias libero ipsa. Unde et et voluptas debitis delectus deleniti.',
    id: '52'
  },
  {
    createdAt: '2021-12-28T06:55:51.421Z',
    name: 'Nathaniel Wilkinson',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '478.00',
    rating: '632936377',
    amount: '574.42',
    category: 'category 53',
    size: 'size 53',
    color: 'gold',
    wearType: 'wearType 53',
    description: 'Totam eius esse incidunt velit.',
    about:
      'Sapiente ipsum doloribus nihil quasi aut. Asperiores esse tenetur temporibus doloribus quia sit at exercitationem molestiae. Tenetur voluptatum dolore cupiditate id quod ut. Totam omnis non quia cupiditate.',
    id: '53'
  },
  {
    createdAt: '2021-12-28T06:37:09.507Z',
    name: 'Maggie Luettgen',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '919.00',
    rating: '084677572',
    amount: '542.39',
    category: 'category 54',
    size: 'size 54',
    color: 'lavender',
    wearType: 'wearType 54',
    description: 'Ea accusamus dolore commodi quaerat dolorem libero.',
    about:
      'Quod est eaque est. Vel distinctio et eum. Et itaque aut iure ratione. Aperiam quis dolore possimus excepturi est sapiente.',
    id: '54'
  },
  {
    createdAt: '2021-12-28T14:02:34.072Z',
    name: 'Bert Schaefer',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '436.00',
    rating: '561009692',
    amount: '15.71',
    category: 'category 55',
    size: 'size 55',
    color: 'orchid',
    wearType: 'wearType 55',
    description: 'Magni ut pariatur vitae natus libero odio fugiat quod.',
    about:
      'Iure sit sequi aut voluptatem itaque minima quis. Adipisci numquam non aut autem nemo voluptas. Unde tempora enim aut. Atque perspiciatis voluptas corrupti ut facere sed facere molestiae molestias.',
    id: '55'
  },
  {
    createdAt: '2021-12-28T00:20:35.676Z',
    name: 'Angel Jones',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '363.00',
    rating: '709930222',
    amount: '468.34',
    category: 'category 56',
    size: 'size 56',
    color: 'tan',
    wearType: 'wearType 56',
    description: 'Quia praesentium harum architecto enim.',
    about: 'Est quam et aliquid. Rerum earum laborum sit quo ea.',
    id: '56'
  },
  {
    createdAt: '2021-12-28T05:38:00.917Z',
    name: 'Jodi Adams',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '606.00',
    rating: '500163081',
    amount: '296.54',
    category: 'category 57',
    size: 'size 57',
    color: 'tan',
    wearType: 'wearType 57',
    description: 'Quia quos beatae mollitia saepe.',
    about:
      'Laboriosam porro veritatis cumque quia dicta et et. Voluptatibus perspiciatis praesentium rerum impedit molestias mollitia recusandae. Vero officia aliquam eligendi. Quos atque et alias laborum facilis omnis est. Et id unde fugit magni delectus quod possimus.',
    id: '57'
  },
  {
    createdAt: '2021-12-28T15:44:36.556Z',
    name: 'Elbert Reichert',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '465.00',
    rating: '254635470',
    amount: '309.17',
    category: 'category 58',
    size: 'size 58',
    color: 'black',
    wearType: 'wearType 58',
    description: 'Dolorem sed porro molestias vel fugiat labore.',
    about:
      'Esse repudiandae sit perspiciatis corrupti minus voluptatum et. Aut itaque deleniti. Dolorum atque fuga vitae dolorem occaecati. Ea doloribus a sapiente et.',
    id: '58'
  },
  {
    createdAt: '2021-12-27T19:24:24.746Z',
    name: 'Christina Carroll I',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '869.00',
    rating: '534047076',
    amount: '682.92',
    category: 'category 59',
    size: 'size 59',
    color: 'lime',
    wearType: 'wearType 59',
    description: 'Et laborum asperiores.',
    about:
      'Sint animi tempore voluptatem beatae sunt est. Aut non voluptate ut id. Animi quo earum commodi veniam aut. Nostrum voluptatem praesentium sed corporis atque. Doloribus et maxime nisi.',
    id: '59'
  },
  {
    createdAt: '2021-12-28T02:26:34.561Z',
    name: 'Amber Metz',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '149.00',
    rating: '704722590',
    amount: '226.14',
    category: 'category 60',
    size: 'size 60',
    color: 'ivory',
    wearType: 'wearType 60',
    description: 'Facilis sequi voluptatem dolorem et voluptas ipsa aperiam quas.',
    about:
      'Consequatur rerum quia eum eveniet itaque exercitationem quia. Maxime sed molestiae aliquam sequi maxime est et. Velit id quibusdam cumque ab iusto dolorem. Quas eligendi vero. Accusantium asperiores consequatur impedit blanditiis.',
    id: '60'
  },
  {
    createdAt: '2021-12-28T13:56:37.791Z',
    name: 'Sophie Nicolas',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '774.00',
    rating: '670549771',
    amount: '403.59',
    category: 'category 61',
    size: 'size 61',
    color: 'lime',
    wearType: 'wearType 61',
    description: 'Hic harum corporis ratione aspernatur quia sed atque.',
    about:
      'Consequatur ducimus et aut delectus. Quod sapiente esse consectetur et ipsam dolore deserunt. Placeat velit voluptatem omnis. Nesciunt sed eaque voluptas. Voluptatem autem rerum illo aliquam.',
    id: '61'
  },
  {
    createdAt: '2021-12-27T16:35:21.607Z',
    name: 'Gary Powlowski',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '255.00',
    rating: '186984451',
    amount: '414.18',
    category: 'category 62',
    size: 'size 62',
    color: 'orchid',
    wearType: 'wearType 62',
    description: 'Dolor illo in at qui nemo aperiam maiores tempora eius.',
    about:
      'Laborum est eligendi debitis itaque praesentium. Quis quia harum. Dolores quasi aperiam sit officia quas delectus eligendi.',
    id: '62'
  },
  {
    createdAt: '2021-12-28T12:09:06.595Z',
    name: 'Mr. Delia Rippin',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '517.00',
    rating: '972466277',
    amount: '643.00',
    category: 'category 63',
    size: 'size 63',
    color: 'teal',
    wearType: 'wearType 63',
    description: 'Quasi dolor dolorum aut fuga ut sit.',
    about:
      'Quod dolor voluptas rerum sunt cupiditate iusto non numquam inventore. Error eligendi fuga omnis est fugit sit inventore autem aperiam.',
    id: '63'
  },
  {
    createdAt: '2021-12-28T01:01:01.370Z',
    name: 'Candace Rolfson',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '4.00',
    rating: '953855959',
    amount: '783.70',
    category: 'category 64',
    size: 'size 64',
    color: 'lavender',
    wearType: 'wearType 64',
    description: 'Repudiandae eaque nihil provident dolor.',
    about:
      'Eum sit totam neque aut officiis similique enim. Et ut autem vero nostrum animi vero ipsam unde. Cumque et repellat tempore quibusdam omnis ducimus.',
    id: '64'
  },
  {
    createdAt: '2021-12-28T05:04:20.991Z',
    name: 'Laurence Gleason',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '588.00',
    rating: '640917870',
    amount: '14.74',
    category: 'category 65',
    size: 'size 65',
    color: 'orchid',
    wearType: 'wearType 65',
    description: 'Suscipit ut nisi veritatis numquam.',
    about:
      'Debitis qui fugiat ut velit est corporis voluptatibus aperiam. Officia aut ipsam fugiat et distinctio ut rerum magnam praesentium. Exercitationem deleniti cum odit. Qui soluta ut in qui consectetur illum voluptatem.',
    id: '65'
  },
  {
    createdAt: '2021-12-28T07:35:16.163Z',
    name: 'Bernice Kuvalis',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '319.00',
    rating: '827231696',
    amount: '947.13',
    category: 'category 66',
    size: 'size 66',
    color: 'red',
    wearType: 'wearType 66',
    description: 'Officia quod architecto sed modi.',
    about: 'Et accusantium aut aliquam voluptatibus. Voluptatem fuga repellendus fugit sint sit ut modi ipsam.',
    id: '66'
  },
  {
    createdAt: '2021-12-28T02:15:19.580Z',
    name: 'Terrell Koelpin',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '856.00',
    rating: '148708811',
    amount: '715.85',
    category: 'category 67',
    size: 'size 67',
    color: 'turquoise',
    wearType: 'wearType 67',
    description: 'Eos dignissimos non voluptatem dolorem est.',
    about: 'Enim maxime est architecto. Libero quibusdam corrupti cupiditate numquam sit harum voluptas.',
    id: '67'
  },
  {
    createdAt: '2021-12-28T12:16:02.786Z',
    name: 'Lois Lakin',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '478.00',
    rating: '671634410',
    amount: '316.51',
    category: 'category 68',
    size: 'size 68',
    color: 'white',
    wearType: 'wearType 68',
    description: 'Necessitatibus quia et consequuntur voluptates.',
    about:
      'Dolor quia voluptas quia nulla eum deserunt neque. Sapiente facilis illo sint sapiente ea eos nulla qui architecto. Amet laborum doloremque veritatis enim facere. Maxime fugit et cum quibusdam consectetur. Numquam omnis et provident pariatur.',
    id: '68'
  },
  {
    createdAt: '2021-12-28T10:26:27.616Z',
    name: 'Wilson Gutkowski',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '125.00',
    rating: '692269738',
    amount: '555.36',
    category: 'category 69',
    size: 'size 69',
    color: 'gold',
    wearType: 'wearType 69',
    description: 'Et maxime dolor et nostrum magni id assumenda at.',
    about:
      'Voluptas facere qui ipsam delectus. Alias ratione minima debitis perferendis incidunt dolores quasi. Alias perspiciatis aut impedit consequatur autem blanditiis debitis qui. Voluptatibus sunt modi et sunt veritatis est. Porro est qui sit nesciunt.',
    id: '69'
  },
  {
    createdAt: '2021-12-27T18:51:15.729Z',
    name: 'Eloise Heaney III',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '809.00',
    rating: '688946162',
    amount: '996.67',
    category: 'category 70',
    size: 'size 70',
    color: 'grey',
    wearType: 'wearType 70',
    description: 'Tempora consequatur ratione.',
    about: 'Sunt asperiores excepturi in. Voluptatum aut qui accusantium ducimus. Accusantium vitae sed.',
    id: '70'
  },
  {
    createdAt: '2021-12-28T09:31:26.508Z',
    name: 'Guadalupe Hermiston',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '97.00',
    rating: '460773472',
    amount: '965.18',
    category: 'category 71',
    size: 'size 71',
    color: 'white',
    wearType: 'wearType 71',
    description: 'Cum sed tenetur.',
    about:
      'Facilis temporibus sed quisquam illum perferendis ad accusamus aliquam itaque. Ullam assumenda voluptate facilis aperiam laborum expedita aut quisquam dicta. Quibusdam quo neque.',
    id: '71'
  },
  {
    createdAt: '2021-12-28T08:45:00.889Z',
    name: 'Allen Ruecker',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '156.00',
    rating: '822843597',
    amount: '936.69',
    category: 'category 72',
    size: 'size 72',
    color: 'green',
    wearType: 'wearType 72',
    description: 'Voluptatem qui aut adipisci.',
    about:
      'Ullam molestiae nihil saepe neque sit repudiandae nemo magnam. Voluptatem nemo eius ut et qui est et. Minus nemo est culpa nam. Vel quae fugit. Autem tenetur est quas corrupti necessitatibus quo quisquam nesciunt sint. Quisquam quia corporis aut ut omnis et labore quaerat autem.',
    id: '72'
  },
  {
    createdAt: '2021-12-28T11:23:05.635Z',
    name: 'Vickie Rosenbaum',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '130.00',
    rating: '171946365',
    amount: '857.18',
    category: 'category 73',
    size: 'size 73',
    color: 'plum',
    wearType: 'wearType 73',
    description: 'Aut accusantium doloribus voluptas sint mollitia.',
    about:
      'Inventore et vel est necessitatibus. Et eos perspiciatis enim hic debitis. Adipisci aut dolor odio natus aut. Qui autem dolores qui incidunt.',
    id: '73'
  },
  {
    createdAt: '2021-12-28T15:45:19.200Z',
    name: 'Mr. Bobby Beahan',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '793.00',
    rating: '347100566',
    amount: '585.34',
    category: 'category 74',
    size: 'size 74',
    color: 'tan',
    wearType: 'wearType 74',
    description: 'Ut eum dolorem odit enim vel qui sit voluptas sint.',
    about:
      'Facilis eum perferendis ut at. Officiis quis et eum consequuntur numquam. Eveniet illo voluptatibus explicabo vitae. Eius et ex natus. Non beatae debitis nostrum repellat dolor animi.',
    id: '74'
  },
  {
    createdAt: '2021-12-28T04:43:11.016Z',
    name: 'Mrs. Ronald Ritchie',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '55.00',
    rating: '276236352',
    amount: '704.11',
    category: 'category 75',
    size: 'size 75',
    color: 'maroon',
    wearType: 'wearType 75',
    description: 'Veniam quia deserunt neque doloremque quasi suscipit sunt dolores.',
    about: 'Inventore doloribus unde asperiores alias. Consequatur corrupti quidem omnis eum.',
    id: '75'
  },
  {
    createdAt: '2021-12-28T03:29:07.528Z',
    name: 'Alice Bechtelar',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '71.00',
    rating: '712793113',
    amount: '104.08',
    category: 'category 76',
    size: 'size 76',
    color: 'salmon',
    wearType: 'wearType 76',
    description: 'Sunt officia mollitia et.',
    about:
      'Natus autem voluptate non in dolore in aut voluptatem in. Aliquid exercitationem et voluptates ipsam at quo et enim.',
    id: '76'
  },
  {
    createdAt: '2021-12-27T16:50:52.670Z',
    name: 'Lila Quigley Sr.',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '156.00',
    rating: '427460511',
    amount: '11.45',
    category: 'category 77',
    size: 'size 77',
    color: 'green',
    wearType: 'wearType 77',
    description: 'Sit dolores sint porro necessitatibus et reiciendis cupiditate et.',
    about:
      'Sit mollitia aut alias. Voluptatem deleniti earum aut doloribus perspiciatis omnis. Sint eum nihil dolore ratione fuga consequatur. Est sit et commodi qui ab mollitia suscipit ullam.',
    id: '77'
  },
  {
    createdAt: '2021-12-28T07:11:32.446Z',
    name: 'Diana Auer',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '501.00',
    rating: '735958582',
    amount: '963.36',
    category: 'category 78',
    size: 'size 78',
    color: 'olive',
    wearType: 'wearType 78',
    description: 'Est dignissimos officia itaque placeat aut quaerat ipsum voluptas.',
    about:
      'Laudantium esse voluptatem voluptas ut qui occaecati dolorem nihil. Eum beatae dolorem illum voluptatibus quas necessitatibus ullam doloremque totam. Aut illum distinctio ad qui aut. Et voluptatem at laboriosam. Quod odit et debitis consectetur repellendus quisquam veritatis. Dolor et et.',
    id: '78'
  },
  {
    createdAt: '2021-12-28T05:54:02.779Z',
    name: 'Damon Russel',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '784.00',
    rating: '271544913',
    amount: '893.60',
    category: 'category 79',
    size: 'size 79',
    color: 'grey',
    wearType: 'wearType 79',
    description: 'Et repudiandae incidunt ut commodi nam rerum eveniet labore.',
    about:
      'Et consequuntur eos reiciendis voluptas. Officia qui ut ea repellat aspernatur ullam quod corrupti. Magnam possimus deserunt distinctio earum cum dolorem hic. Perferendis occaecati sed. Quae vitae atque vel totam aspernatur molestias ut sequi.',
    id: '79'
  },
  {
    createdAt: '2021-12-27T18:36:57.219Z',
    name: 'Dr. Mary Lind',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '405.00',
    rating: '790405025',
    amount: '270.66',
    category: 'category 80',
    size: 'size 80',
    color: 'tan',
    wearType: 'wearType 80',
    description: 'Tempora voluptas architecto qui temporibus rerum et voluptatum inventore sit.',
    about: 'Officiis dolores quia non ea. Et voluptatem unde omnis rerum omnis ut sed. Omnis dolorem corrupti illum.',
    id: '80'
  },
  {
    createdAt: '2021-12-27T18:44:57.765Z',
    name: 'Estelle Nicolas',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '278.00',
    rating: '039398479',
    amount: '680.20',
    category: 'category 81',
    size: 'size 81',
    color: 'pink',
    wearType: 'wearType 81',
    description: 'Alias dolorum tenetur amet sapiente.',
    about:
      'Autem qui necessitatibus. Cupiditate ab id nulla et officiis magni autem culpa. Totam necessitatibus consequatur.',
    id: '81'
  },
  {
    createdAt: '2021-12-27T21:23:45.025Z',
    name: 'Curtis Brakus',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '959.00',
    rating: '152965611',
    amount: '212.17',
    category: 'category 82',
    size: 'size 82',
    color: 'pink',
    wearType: 'wearType 82',
    description: 'Aut qui est et dignissimos ipsa in quis.',
    about: 'Consequatur rem amet laboriosam labore quia et molestiae et aliquid. Asperiores fugiat ullam.',
    id: '82'
  },
  {
    createdAt: '2021-12-28T02:42:05.182Z',
    name: 'Marguerite Bayer',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '154.00',
    rating: '149390901',
    amount: '878.00',
    category: 'category 83',
    size: 'size 83',
    color: 'violet',
    wearType: 'wearType 83',
    description: 'Omnis omnis sed sit.',
    about:
      'Ipsum iusto sit fugit quaerat ipsam assumenda dolorum. Pariatur sit est. Itaque repellendus molestiae. At ipsam quos aut iure. Culpa voluptatem cumque.',
    id: '83'
  },
  {
    createdAt: '2021-12-28T01:46:33.694Z',
    name: 'Sonya Dare',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '463.00',
    rating: '906632475',
    amount: '40.33',
    category: 'category 84',
    size: 'size 84',
    color: 'indigo',
    wearType: 'wearType 84',
    description: 'Et expedita aut officia laudantium ut officiis.',
    about: 'Commodi ut ullam voluptas aut. Debitis quos autem voluptatem est aut.',
    id: '84'
  },
  {
    createdAt: '2021-12-28T11:22:05.923Z',
    name: 'Viola Schimmel',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '519.00',
    rating: '702401279',
    amount: '246.80',
    category: 'category 85',
    size: 'size 85',
    color: 'cyan',
    wearType: 'wearType 85',
    description: 'Beatae deleniti consequuntur ut similique ea.',
    about:
      'Nesciunt ea expedita eligendi nostrum laborum. Eius molestias minus consequatur doloremque rerum. Itaque voluptate laboriosam corporis eveniet. Corrupti aut consequatur explicabo vel deleniti eum sint. Mollitia illo quas.',
    id: '85'
  },
  {
    createdAt: '2021-12-28T06:30:39.693Z',
    name: 'Tyler Parker',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '846.00',
    rating: '769113403',
    amount: '458.55',
    category: 'category 86',
    size: 'size 86',
    color: 'tan',
    wearType: 'wearType 86',
    description: 'Ratione omnis officia sapiente omnis.',
    about: 'Rem numquam aut optio eum a. Et ex id.',
    id: '86'
  },
  {
    createdAt: '2021-12-28T05:00:13.528Z',
    name: 'Walter Fay',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '680.00',
    rating: '198459071',
    amount: '136.56',
    category: 'category 87',
    size: 'size 87',
    color: 'orange',
    wearType: 'wearType 87',
    description: 'Ea vero voluptatibus et impedit.',
    about:
      'Optio enim consequatur iusto. Dicta aut nemo quis ducimus. Est nam exercitationem quisquam libero reiciendis in molestiae qui. In consequuntur omnis nihil dolorem fugiat beatae. Recusandae qui eveniet deserunt consequatur et commodi.',
    id: '87'
  },
  {
    createdAt: '2021-12-28T09:51:36.888Z',
    name: 'Denise Renner',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '408.00',
    rating: '004459013',
    amount: '205.83',
    category: 'category 88',
    size: 'size 88',
    color: 'blue',
    wearType: 'wearType 88',
    description: 'Similique ex accusamus qui sit rem eos et.',
    about:
      'Impedit qui odio officia eaque incidunt dolor et. Doloribus at exercitationem est ad architecto consequatur dolorem dolores in. Eum in aspernatur exercitationem non. Voluptatem enim est doloribus magni quia. Saepe qui et veniam exercitationem quos natus corrupti. Expedita quibusdam eaque doloribus.',
    id: '88'
  },
  {
    createdAt: '2021-12-27T21:58:22.943Z',
    name: 'Mack Lueilwitz',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '949.00',
    rating: '008461230',
    amount: '238.60',
    category: 'category 89',
    size: 'size 89',
    color: 'gold',
    wearType: 'wearType 89',
    description: 'Soluta et illum.',
    about:
      'Adipisci laudantium ex. Et velit voluptatibus veritatis soluta animi numquam. Voluptatem fugit ipsam ab. Alias aperiam sed accusamus quisquam autem vel quisquam nostrum.',
    id: '89'
  },
  {
    createdAt: '2021-12-28T09:11:07.358Z',
    name: 'Mae Nitzsche',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '535.00',
    rating: '365923822',
    amount: '197.68',
    category: 'category 90',
    size: 'size 90',
    color: 'olive',
    wearType: 'wearType 90',
    description: 'Eum et omnis voluptatem ea ut saepe perferendis.',
    about:
      'Consequatur sunt quis nihil dolorum. Porro voluptas qui quia vel vitae quidem. Dolorum velit repellendus modi magni eveniet laboriosam. Saepe doloribus quis autem itaque suscipit.',
    id: '90'
  },
  {
    createdAt: '2021-12-27T16:14:33.725Z',
    name: 'Willard Heller',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '282.00',
    rating: '985419237',
    amount: '331.11',
    category: 'category 91',
    size: 'size 91',
    color: 'turquoise',
    wearType: 'wearType 91',
    description: 'Tempore sed quibusdam.',
    about:
      'Quae quia aspernatur. Ipsa dolorem omnis ex unde. Ut odio repellat. Quae voluptatem ullam magnam. Officia placeat et quidem eaque totam maxime doloribus ut aliquid.',
    id: '91'
  },
  {
    createdAt: '2021-12-28T14:46:32.595Z',
    name: 'Kristina Gutmann',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '408.00',
    rating: '594629858',
    amount: '394.75',
    category: 'category 92',
    size: 'size 92',
    color: 'lime',
    wearType: 'wearType 92',
    description: 'Et nemo excepturi molestias a sit autem sit deserunt qui.',
    about:
      'Qui dolor sed consectetur exercitationem fugiat enim. Blanditiis voluptatem et sed ratione itaque ut voluptas nulla. Odio voluptatem asperiores rerum iure natus quibusdam deleniti. Officia recusandae non autem quia quisquam.',
    id: '92'
  },
  {
    createdAt: '2021-12-28T05:28:06.558Z',
    name: 'Carlos Koepp IV',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '212.00',
    rating: '776423801',
    amount: '57.11',
    category: 'category 93',
    size: 'size 93',
    color: 'white',
    wearType: 'wearType 93',
    description: 'Quo dolore cum.',
    about:
      'Nihil nobis perspiciatis omnis explicabo architecto voluptate. Amet id amet quae saepe voluptatem libero ut. Molestiae est sed. Sit consequatur occaecati et exercitationem et et. Illo tenetur quasi quaerat.',
    id: '93'
  },
  {
    createdAt: '2021-12-27T17:59:09.946Z',
    name: 'Martha Sawayn',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '276.00',
    rating: '989923130',
    amount: '50.90',
    category: 'category 94',
    size: 'size 94',
    color: 'maroon',
    wearType: 'wearType 94',
    description: 'Accusantium libero aspernatur voluptatem fugiat.',
    about:
      'Minima et voluptatem dolorem. Exercitationem commodi rerum voluptatem saepe fugiat. Pariatur libero dolorem magnam blanditiis eius. Ipsam omnis et deleniti hic. Non sequi cumque dolorum natus.',
    id: '94'
  },
  {
    createdAt: '2021-12-27T22:08:39.238Z',
    name: 'Santos Hyatt',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '405.00',
    rating: '161667447',
    amount: '913.22',
    category: 'category 95',
    size: 'size 95',
    color: 'silver',
    wearType: 'wearType 95',
    description: 'Est nobis vitae voluptatum laudantium aut ea ut placeat corporis.',
    about:
      'Mollitia quia similique et eaque libero soluta quia. Eos eos esse adipisci dolores alias. Adipisci qui sunt qui ullam. Eaque ab error iusto et aut culpa. Corrupti dignissimos est sunt. Nemo dolores placeat eligendi quis impedit nobis.',
    id: '95'
  },
  {
    createdAt: '2021-12-28T10:59:08.811Z',
    name: 'Samuel Paucek',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '744.00',
    rating: '365866293',
    amount: '201.02',
    category: 'category 96',
    size: 'size 96',
    color: 'blue',
    wearType: 'wearType 96',
    description: 'Vero officia culpa magnam in at.',
    about: 'Voluptatum neque qui. Est eveniet ad et minima quibusdam.',
    id: '96'
  },
  {
    createdAt: '2021-12-27T19:26:01.031Z',
    name: 'Jessica Kerluke',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '414.00',
    rating: '096465125',
    amount: '63.01',
    category: 'category 97',
    size: 'size 97',
    color: 'teal',
    wearType: 'wearType 97',
    description: 'Eos aut doloribus dolorem quisquam at.',
    about:
      'Qui ut iure. Iure et quod accusantium deleniti non vel. Provident maxime eveniet. Et voluptatem fuga cum corporis sint dolor quia tempore. Eaque dolor quisquam laboriosam at nesciunt fugiat esse quo.',
    id: '97'
  },
  {
    createdAt: '2021-12-28T11:29:48.949Z',
    name: 'Lynn Roob',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '185.00',
    rating: '684160696',
    amount: '325.08',
    category: 'category 98',
    size: 'size 98',
    color: 'pink',
    wearType: 'wearType 98',
    description: 'Itaque rerum dolore aut eligendi dignissimos architecto et exercitationem.',
    about: 'Ex et ad at. Architecto nihil consectetur a asperiores in voluptas. Impedit ullam modi aperiam.',
    id: '98'
  },
  {
    createdAt: '2021-12-28T10:55:48.490Z',
    name: 'Nadine Fadel',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '123.00',
    rating: '497133315',
    amount: '845.10',
    category: 'category 99',
    size: 'size 99',
    color: 'lavender',
    wearType: 'wearType 99',
    description: 'Dolore suscipit odit ex voluptas numquam modi.',
    about:
      'Quos similique provident praesentium. Repellendus voluptate non explicabo qui eius doloribus. Et adipisci quisquam eum dolorem voluptatum.',
    id: '99'
  },
  {
    createdAt: '2021-12-28T12:16:09.177Z',
    name: 'Thelma Howell',
    photo: 'http://placeimg.com/640/480/fashion',
    price: '391.00',
    rating: '315559877',
    amount: '202.76',
    category: 'category 100',
    size: 'size 100',
    color: 'gold',
    wearType: 'wearType 100',
    description: 'Et nihil voluptate voluptas.',
    about: 'Et nam vitae sapiente expedita. Minus autem quia a ipsum vero. Dignissimos aspernatur ea ex tempora.',
    id: '100'
  }
];
const sizes = ['xs', 's', 'm', 'l', 'sl', 'xl', 'xxl'];
const colors = ['black', 'white', 'blue', 'yellow', 'orange'];
const wearType = ['women', 'men', 'kids', 'jewellery', 'accessories'];
const categories = ['accessories', 'dresses', 'women', 'men', 'watch', 'clothing', 'bags'];

const news = test.map(item => {
  return {
    ...item,
    rating: Math.round(Math.random() * 5),
    category: categories[Math.floor(Math.random() * categories.length)],
    wearType: wearType[Math.floor(Math.random() * categories.length)],
    colors: colors[Math.floor(Math.random() * colors.length)],
    size: sizes[Math.floor(Math.random() * sizes.length)]
  };
});

export { news };
